In [4]:
import numpy as np
A = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(A)
w, v

(array([2., 3.]),
 array([[-0.89442719,  0.83205029],
        [ 0.4472136 , -0.5547002 ]]))

In [5]:
A = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
v, _ = np.linalg.eig(A)
print(v)

[ 3. -3.  3.]


In [6]:
vect = np.array([3, -3, -4])
print(f'A * vect = {A.dot(vect)}')
print(f'lambda1 * vect = {v[0] * vect}')
print(f'lambda2 * vect = {v[1] * vect}')
print(f'lambda3 * vect = {v[2] * vect}')

A * vect = [ -9   9 -12]
lambda1 * vect = [  9.  -9. -12.]
lambda2 * vect = [-9.  9. 12.]
lambda3 * vect = [  9.  -9. -12.]


In [7]:
b = np.array([[1, 1], [-1, 3]])
v, w = np.linalg.eig(A)
w

array([[ 0.70710678, -0.70710678,  0.        ],
       [ 0.70710678,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])